#line 0 "src/main/settings/custom_settings.cpp"
#include "src/main/settings/custom_settings.cpp"

#line 0 "src/main/settings/autogenerated_settings.cpp"
#include "src/main/settings/autogenerated_settings.cpp"

